apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: iscas.notnull.io
spec:
  group: notnull.io
  names:
    kind: isca
    listKind: IscaList
    plural: iscas
    singular: isca
  scope: Namespaced/Cluster
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            properties:
              registry:
                $ref: './components-crd.yaml#/components/schemas/registry'
              pulling:
                $ref: './components-crd.yaml#/components/schemas/pulling'
              rollback:
                $ref: './components-crd.yaml#/components/schemas/rollback'
              weebhook:
                $ref: './components-crd.yaml#/components/schemas/weebhook'
